In [1]:
import numpy as np 

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
print(a)

[1 2 3 4 5]


In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.full((5,2), 7)

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

In [8]:
np.shape(a)

(5,)

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.random.rand(2,5)

array([[0.42295266, 0.93707874, 0.3084069 , 0.19868151, 0.5207157 ],
       [0.33155242, 0.45447099, 0.58479083, 0.12733342, 0.06901342]])

In [11]:
np.random.randint(2,6)

3

Array properties

In [12]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)


1
(5,)
5
int64


In [13]:
a.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [14]:
a.flatten()

array([1, 2, 3, 4, 5])

In [15]:
x = np.arange(1,10)
y = np.arange(11,20)

In [16]:
print(x+y)
print(x*y)
print(x/y)
print(x-y)

[12 14 16 18 20 22 24 26 28]
[ 11  24  39  56  75  96 119 144 171]
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421]
[-10 -10 -10 -10 -10 -10 -10 -10 -10]


In [17]:
x**(y)

array([                  1,                4096,             1594323,
                 268435456,         30517578125,       2821109907456,
           232630513987207,   18014398509481984, 1350851717672992089])

In [18]:
y

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
print(np.sum(x))
print(np.mean(x))
print(np.median(x))     
print(np.std(x))
print(np.var(x))
print(np.min(x))
print(np.max(x))
print(np.corrcoef(x,y))
print(np.sort(x))
print(np.unique(x))

45
5.0
5.0
2.581988897471611
6.666666666666667
1
9
[[1. 1.]
 [1. 1.]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [20]:
np.sum(y, axis=0)

np.int64(135)

In [21]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.sum(c, axis=1)

array([ 6, 15, 24])

In [22]:
o = np.arange(1,11)
np.sum(o, axis=0)

np.int64(55)

In [23]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [24]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [25]:
arr1.size

10

In [26]:
len(arr1)

2

In [27]:
np.max(arr1)

np.int64(10)